# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_a9jnuRy2EACxlS1KFRu19Gu7lClrR0
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

!pip install chembl_webresource_client

import pandas as pd
from chembl_webresource_client.new_client import new_client

target = new_client.target
target_query = target.search("JAK2")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

selected_target = targets.target_chembl_id[4]
selected_target

activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

df1 = pd.DataFrame.from_dict(results)
df1.head(5)

df1.standard_type.unique()

df1.to_csv('bioactivity_raw_data.csv', index=False)

! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

! head bioactivity_raw_data.csv

df1["standard_type"].isna().sum()

df2 = df1[df1["standard_value"].notna()]
df2.head()

bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"